import { AlertRow, ForecastRow, FreezeRow, SnapshotData } from './types'

const TODAY = new Date().toISOString().slice(0, 10)

function addDays(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString().slice(0, 10)
}

export const sampleSnapshot: SnapshotData = {
  total_headcount: 80,
  run_date: TODAY,
  status_counts: { available: 6, proposed: 19, allocated: 4, nafd: 29, other: 22 },
  current_vs_future: { 'Current bench': 39, 'Future bench': 41 },
  aging_distribution: { '>91 days': 39, 'Unknown': 41 },
  by_location: { Onsite: 63, Offshore: 17 },
}

export const sampleForecast: ForecastRow[] = Array.from({ length: 91 }, (_, i) => ({
  forecast_date: addDays(i),
  days_from_today: i,
  total_forecast_bench: i >= 88 ? 1 : 0,
  confirmed_count: i >= 88 ? 1 : 0,
  projected_count: 0,
  forecast_confidence_band: 'HIGH',
  bucket: i <= 30 ? '30d' : i <= 60 ? '60d' : '90d',
}))

export const sampleAlerts: AlertRow[] = [
  { org_slice: 'CYBER_SEC',      current_bench_count: 6, bench_threshold: 3,  breach_amount:  3, is_breached: true,  alert_severity: 'MEDIUM', recommended_action: 'Review bench pipeline for CYBER_SEC. Current bench (6) exceeds threshold (3) by 3. Consider hiring freeze advisory.', run_date: TODAY },
  { org_slice: 'DIGITAL_ENG',    current_bench_count: 4, bench_threshold: 5,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'CLOUD_INFRA',    current_bench_count: 3, bench_threshold: 4,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'DATA_ANALYTICS', current_bench_count: 5, bench_threshold: 6,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'JAVA_PRACTICE',  current_bench_count: 7, bench_threshold: 8,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'QA_AUTOMATION',  current_bench_count: 3, bench_threshold: 4,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'SAP_PRACTICE',   current_bench_count: 9, bench_threshold: 10, breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'DEVOPS_SRE',     current_bench_count: 2, bench_threshold: 3,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'MOBILE_DEV',     current_bench_count: 2, bench_threshold: 3,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'AI_ML',          current_bench_count: 4, bench_threshold: 5,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'FULLSTACK_WEB',  current_bench_count: 6, bench_threshold: 7,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'ERP_FUNCTIONAL', current_bench_count: 3, bench_threshold: 4,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'TESTING_PERF',   current_bench_count: 2, bench_threshold: 3,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
  { org_slice: 'ARCHITECTURE',   current_bench_count: 1, bench_threshold: 2,  breach_amount: -1, is_breached: false, alert_severity: 'OK',     recommended_action: 'No action required.', run_date: TODAY },
]

export const sampleFreeze: FreezeRow[] = [
  { skill: 'ERP-SAP',       bench_count: 7, near_term_releases: 0, total_supply: 7, open_demand_count: 2, supply_surplus:  5, freeze_recommended: true,  avg_skill_rating: 1.5, advisory_note: 'Supply (7) exceeds demand (2) by 5 for ERP-SAP. Recommend hiring pause.',           run_date: TODAY, llm_narrative: 'Implement an immediate hiring freeze for ERP-SAP. Bench surplus of 5 vs demand 2. Low avg rating 1.5 indicates upskilling priority. Review: 30-day.' },
  { skill: 'Selenium',      bench_count: 5, near_term_releases: 0, total_supply: 5, open_demand_count: 2, supply_surplus:  3, freeze_recommended: true,  avg_skill_rating: 3.5, advisory_note: 'Supply (5) exceeds demand (2) by 3 for Selenium. Recommend hiring pause.',           run_date: TODAY, llm_narrative: 'Apply targeted hiring freeze for Selenium. Surplus 3, avg rating 3.5 — competent bench available. Defer hires. Review: 30-day.' },
  { skill: 'Spring Boot',   bench_count: 5, near_term_releases: 0, total_supply: 5, open_demand_count: 3, supply_surplus:  2, freeze_recommended: true,  avg_skill_rating: 3.0, advisory_note: 'Supply (5) exceeds demand (3) by 2 for Spring Boot. Recommend hiring pause.',         run_date: TODAY, llm_narrative: 'Enact hiring freeze for Spring Boot except critical needs. Surplus 2, avg rating 3.0. Review: 60-day.' },
  { skill: 'Docker',        bench_count: 4, near_term_releases: 0, total_supply: 4, open_demand_count: 3, supply_surplus:  1, freeze_recommended: true,  avg_skill_rating: 3.0, advisory_note: 'Supply (4) exceeds demand (3) by 1 for Docker. Recommend hiring pause.',             run_date: TODAY, llm_narrative: 'Initiate hiring freeze for Docker unless urgent. Surplus 1. Evaluate redeployment. Review: 60-day.' },
  { skill: 'AWS',           bench_count: 4, near_term_releases: 0, total_supply: 4, open_demand_count: 3, supply_surplus:  1, freeze_recommended: true,  avg_skill_rating: 2.0, advisory_note: 'Supply (4) exceeds demand (3) by 1 for AWS. Recommend hiring pause.',               run_date: TODAY, llm_narrative: 'Freeze AWS hiring except critical cloud initiatives. Surplus 1. Review: 60-day.' },
  { skill: 'Microservices', bench_count: 4, near_term_releases: 0, total_supply: 4, open_demand_count: 3, supply_surplus:  1, freeze_recommended: true,  avg_skill_rating: 1.0, advisory_note: 'Supply (4) exceeds demand (3) by 1 for Microservices. Recommend hiring pause.',     run_date: TODAY, llm_narrative: 'Suspend Microservices hiring. Surplus 1, very low avg rating 1.0 — focus reskilling. Review: 60-day.' },
  { skill: 'MySQL',         bench_count: 3, near_term_releases: 0, total_supply: 3, open_demand_count: 2, supply_surplus:  1, freeze_recommended: true,  avg_skill_rating: 1.5, advisory_note: 'Supply (3) exceeds demand (2) by 1 for MySQL. Recommend hiring pause.',             run_date: TODAY, llm_narrative: 'Impose hiring freeze for MySQL. Surplus 1, avg rating 1.5. Review: 60-day.' },
  { skill: 'Apache Spark',  bench_count: 4, near_term_releases: 0, total_supply: 4, open_demand_count: 3, supply_surplus:  1, freeze_recommended: true,  avg_skill_rating: 1.5, advisory_note: 'Supply (4) exceeds demand (3) by 1 for Apache Spark. Recommend hiring pause.',      run_date: TODAY, llm_narrative: 'Pause Apache Spark hiring until bench reallocated. Surplus 1. Review: 60-day.' },
  { skill: 'Java',          bench_count: 2, near_term_releases: 0, total_supply: 2, open_demand_count: 8, supply_surplus: -6, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (8) exceeds supply (2) by 6 for Java. No freeze needed.',                   run_date: TODAY },
  { skill: 'Python',        bench_count: 3, near_term_releases: 0, total_supply: 3, open_demand_count: 9, supply_surplus: -6, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (9) exceeds supply (3) by 6 for Python. No freeze needed.',                 run_date: TODAY },
  { skill: 'React',         bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 6, supply_surplus: -5, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (6) exceeds supply (1) by 5 for React. No freeze needed.',                   run_date: TODAY },
  { skill: 'Angular',       bench_count: 2, near_term_releases: 0, total_supply: 2, open_demand_count: 5, supply_surplus: -3, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (5) exceeds supply (2) by 3 for Angular. No freeze needed.',                 run_date: TODAY },
  { skill: 'Node.js',       bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 4, supply_surplus: -3, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (4) exceeds supply (1) by 3 for Node.js. No freeze needed.',                 run_date: TODAY },
  { skill: 'Kubernetes',    bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 3, supply_surplus: -3, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (3) exceeds supply (0) by 3 for Kubernetes. No freeze needed.',              run_date: TODAY },
  { skill: 'Terraform',     bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 3, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (3) exceeds supply (1) by 2 for Terraform. No freeze needed.',               run_date: TODAY },
  { skill: 'PostgreSQL',    bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 3, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (3) exceeds supply (1) by 2 for PostgreSQL. No freeze needed.',             run_date: TODAY },
  { skill: 'Snowflake',     bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 2, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (0) by 2 for Snowflake. No freeze needed.',              run_date: TODAY },
  { skill: 'Tableau',       bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 3, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (3) exceeds supply (1) by 2 for Tableau. No freeze needed.',                run_date: TODAY },
  { skill: 'Power BI',      bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 2, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (0) by 2 for Power BI. No freeze needed.',              run_date: TODAY },
  { skill: 'Azure',         bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 3, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (3) exceeds supply (1) by 2 for Azure. No freeze needed.',                  run_date: TODAY },
  { skill: 'Scala',         bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 2, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (0) by 2 for Scala. No freeze needed.',                  run_date: TODAY },
  { skill: 'Go Lang',       bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 2, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (0) by 2 for Go Lang. No freeze needed.',                run_date: TODAY },
  { skill: 'TypeScript',    bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 3, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (3) exceeds supply (1) by 2 for TypeScript. No freeze needed.',             run_date: TODAY },
  { skill: 'Kafka',         bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 2, supply_surplus: -2, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (0) by 2 for Kafka. No freeze needed.',                  run_date: TODAY },
  { skill: 'MongoDB',       bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 2, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (1) by 1 for MongoDB. No freeze needed.',                run_date: TODAY },
  { skill: 'Redis',         bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Redis. No freeze needed.',                  run_date: TODAY },
  { skill: 'Cassandra',     bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Cassandra. No freeze needed.',              run_date: TODAY },
  { skill: 'GraphQL',       bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for GraphQL. No freeze needed.',               run_date: TODAY },
  { skill: 'Spark SQL',     bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Spark SQL. No freeze needed.',             run_date: TODAY },
  { skill: 'Hive',          bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Hive. No freeze needed.',                  run_date: TODAY },
  { skill: 'Jenkins',       bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Jenkins. No freeze needed.',               run_date: TODAY },
  { skill: 'Ansible',       bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Ansible. No freeze needed.',               run_date: TODAY },
  { skill: 'Splunk',        bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Splunk. No freeze needed.',                run_date: TODAY },
  { skill: 'Dynatrace',     bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Dynatrace. No freeze needed.',             run_date: TODAY },
  { skill: 'JMeter',        bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for JMeter. No freeze needed.',                run_date: TODAY },
  { skill: 'Postman',       bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 2, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (1) by 1 for Postman. No freeze needed.',               run_date: TODAY },
  { skill: 'Cucumber',      bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Cucumber. No freeze needed.',              run_date: TODAY },
  { skill: 'TestNG',        bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 2, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (1) by 1 for TestNG. No freeze needed.',                run_date: TODAY },
  { skill: 'Maven',         bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Maven. No freeze needed.',                 run_date: TODAY },
  { skill: 'REST API',      bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 2, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (1) by 1 for REST API. No freeze needed.',              run_date: TODAY },
  { skill: 'gRPC',          bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for gRPC. No freeze needed.',                  run_date: TODAY },
  { skill: 'CQRS',          bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for CQRS. No freeze needed.',                  run_date: TODAY },
  { skill: 'Hadoop',        bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Hadoop. No freeze needed.',                run_date: TODAY },
  { skill: 'GitLab CI',     bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for GitLab CI. No freeze needed.',             run_date: TODAY },
  { skill: 'Chef',          bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Chef. No freeze needed.',                  run_date: TODAY },
  { skill: 'Puppet',        bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Puppet. No freeze needed.',                run_date: TODAY },
  { skill: 'AppDynamics',   bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for AppDynamics. No freeze needed.',          run_date: TODAY },
  { skill: 'Selenium Grid', bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Selenium Grid. No freeze needed.',        run_date: TODAY },
  { skill: 'SoapUI',        bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for SoapUI. No freeze needed.',               run_date: TODAY },
  { skill: 'MyBatis',       bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for MyBatis. No freeze needed.',              run_date: TODAY },
  { skill: 'Hibernate',     bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 2, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (1) by 1 for Hibernate. No freeze needed.',             run_date: TODAY },
  { skill: 'Swift',         bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Swift. No freeze needed.',                run_date: TODAY },
  { skill: 'Kotlin',        bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Kotlin. No freeze needed.',               run_date: TODAY },
  { skill: 'Ruby',          bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Ruby. No freeze needed.',                 run_date: TODAY },
  { skill: 'Spring MVC',    bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 2, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (1) by 1 for Spring MVC. No freeze needed.',            run_date: TODAY },
  { skill: 'JPA',           bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for JPA. No freeze needed.',                  run_date: TODAY },
  { skill: 'Gradle',        bench_count: 0, near_term_releases: 0, total_supply: 0, open_demand_count: 1, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (1) exceeds supply (0) by 1 for Gradle. No freeze needed.',               run_date: TODAY },
  { skill: 'SOAP',          bench_count: 1, near_term_releases: 0, total_supply: 1, open_demand_count: 2, supply_surplus: -1, freeze_recommended: false, avg_skill_rating: null, advisory_note: 'Demand (2) exceeds supply (1) by 1 for SOAP. No freeze needed.',                 run_date: TODAY },
]
