import { useEffect, useState } from 'react'
import axios from 'axios'
import { MeetingAgenda, MeetingAgendaSection } from '../types'

interface Props {
  onClose: () => void
}

function buildCopyText(agenda: MeetingAgenda): string {
  const lines: string[] = [
    'WEEKLY BENCH REVIEW MEETING AGENDA',
    `Date: ${agenda.meeting_date_human}`,
    `Prepared by: ${agenda.prepared_by}`,
    `Total Duration: ${agenda.total_duration_mins} minutes`,
    '=====================================',
    '',
  ]
  for (const section of agenda.sections) {
    lines.push(`${section.section} (${section.duration_mins} min)`)
    for (const point of section.points) {
      lines.push(`   • ${point}`)
    }
    lines.push('')
  }
  lines.push('[Advisory only — Generated by Bench Agent]')
  return lines.join('\n')
}

function SectionPanel({ section }: { section: MeetingAgendaSection }) {
  const [open, setOpen] = useState(true)

  return (
    <div className="agenda-section-panel">
      <div className="agenda-section-header" onClick={() => setOpen((o) => !o)}>
        <span className="agenda-section-title">{section.section}</span>
        <span className="agenda-duration-badge">{section.duration_mins} min</span>
        <span className="expand-chevron" style={{ marginLeft: 6, color: 'var(--text-4)', fontSize: 10 }}>
          {open ? '▼' : '▶'}
        </span>
      </div>
      {open && (
        <ul className="agenda-points-list">
          {section.points.map((point, i) => (
            <li key={i} className="agenda-point-item">{point}</li>
          ))}
        </ul>
      )}
    </div>
  )
}

export default function AgendaModal({ onClose }: Props) {
  const [agenda, setAgenda]   = useState<MeetingAgenda | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState<string | null>(null)
  const [copied, setCopied]   = useState(false)

  useEffect(() => {
    axios.get<MeetingAgenda>('/api/bench/meeting-agenda')
      .then((res) => { setAgenda(res.data); setLoading(false) })
      .catch(() => { setError('Failed to load agenda. Check that the API server is running.'); setLoading(false) })
  }, [])

  function handleCopy() {
    if (!agenda) return
    navigator.clipboard.writeText(buildCopyText(agenda)).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  function handleOverlayClick(e: React.MouseEvent<HTMLDivElement>) {
    if (e.target === e.currentTarget) onClose()
  }

  return (
    <div className="modal-overlay" onClick={handleOverlayClick}>
      <div className="modal-container" role="dialog" aria-modal="true">

        <div className="modal-header">
          <div>
            <div className="modal-title">{agenda?.meeting_title ?? 'Weekly Bench Review'}</div>
            {agenda && (
              <div className="modal-subtitle">
                {agenda.meeting_date_human} &nbsp;·&nbsp; {agenda.total_duration_mins} min &nbsp;·&nbsp; {agenda.prepared_by}
              </div>
            )}
          </div>
          <button className="modal-close-btn" onClick={onClose} aria-label="Close modal">✕</button>
        </div>

        <div className="modal-body">
          {loading && <div className="modal-loading">Loading agenda…</div>}
          {error   && <div className="modal-error">{error}</div>}

          {agenda && (
            <>
              {agenda.sections.map((section, i) => (
                <SectionPanel key={i} section={section} />
              ))}
              <div className="digest-advisory" style={{ marginTop: 8 }}>{agenda.disclaimer}</div>
            </>
          )}
        </div>

        <div className="modal-footer">
          <button className="modal-cancel-btn" onClick={onClose}>Close</button>
          <button className="copy-btn" onClick={handleCopy} disabled={!agenda || loading}>
            {copied ? '✓ Copied!' : 'Copy Agenda'}
          </button>
        </div>
      </div>
    </div>
  )
}
