import { useEffect, useState } from 'react'
import axios from 'axios'
import { DigestReport } from '../types'

interface Props {
  onClose: () => void
}

const HEALTH_CSS: Record<string, string> = {
  HEALTHY: 'health-healthy',
  WATCH: 'health-watch',
  CRITICAL: 'health-critical',
}

function buildCopyText(digest: DigestReport): string {
  const lines: string[] = [
    'BENCH AGENT DAILY INTELLIGENCE REPORT',
    `Date: ${digest.report_date}`,
    '=====================================',
    '',
    'EXECUTIVE SUMMARY',
    digest.executive_summary,
    '',
    `BENCH HEALTH: ${digest.bench_health.status}`,
    `Total Bench: ${digest.bench_health.total_bench} | Current: ${digest.bench_health.current_bench} | Future: ${digest.bench_health.future_bench} | At Risk: ${digest.bench_health.at_risk_count}`,
    '',
    'TOP IMMEDIATE ACTIONS',
  ]

  if (digest.top_actions.length === 0) {
    lines.push('- None')
  } else {
    digest.top_actions.forEach((a, i) => lines.push(`${i + 1}. ${a.action}`))
  }

  lines.push('', 'THRESHOLD BREACHES')
  if (digest.threshold_breaches.length === 0) {
    lines.push('- None')
  } else {
    digest.threshold_breaches.forEach(b => {
      const sign = b.breach_amount > 0 ? '+' : ''
      lines.push(`- ${b.org_slice}: bench=${b.current_bench_count}, threshold=${b.bench_threshold}, breach=${sign}${b.breach_amount} (${b.alert_severity})`)
    })
  }

  lines.push('', 'HIRING FREEZE RECOMMENDATIONS')
  if (digest.freeze_recommendations.length === 0) {
    lines.push('- None')
  } else {
    digest.freeze_recommendations.forEach(f => {
      const sign = f.supply_surplus > 0 ? '+' : ''
      lines.push(`- ${f.skill}: supply=${f.total_supply}, demand=${f.open_demand_count}, surplus=${sign}${f.supply_surplus}`)
    })
  }

  lines.push('', `RELEASES IN NEXT 30 DAYS: ${digest.releases_in_30_days}`, '', '[Advisory only — generated by Bench Agent]')
  return lines.join('\n')
}

export default function DigestModal({ onClose }: Props) {
  const [digest, setDigest]   = useState<DigestReport | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState<string | null>(null)
  const [copied, setCopied]   = useState(false)

  function handleDownloadTxt() {
    if (!digest) return
    const text = buildCopyText(digest)
    const date = new Date().toISOString().slice(0, 10).replace(/-/g, '')
    const blob = new Blob([text], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `BenchAgent_DailyReport_${date}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  useEffect(() => {
    axios.get<DigestReport>('/api/bench/digest')
      .then(res => { setDigest(res.data); setLoading(false) })
      .catch(() => { setError('Failed to load report. Check that the API server is running.'); setLoading(false) })
  }, [])

  function handleCopy() {
    if (!digest) return
    navigator.clipboard.writeText(buildCopyText(digest)).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  function handleOverlayClick(e: React.MouseEvent<HTMLDivElement>) {
    if (e.target === e.currentTarget) onClose()
  }

  return (
    <div className="modal-overlay" onClick={handleOverlayClick}>
      <div className="modal-container" role="dialog" aria-modal="true">

        <div className="modal-header">
          <div>
            <div className="modal-title">{digest?.report_title ?? 'Daily Intelligence Report'}</div>
            {digest && (
              <div className="modal-subtitle">
                Generated: {digest.generated_at.slice(0, 16).replace('T', ' ')} UTC
              </div>
            )}
          </div>
          <button className="modal-close-btn" onClick={onClose} aria-label="Close modal">✕</button>
        </div>

        <div className="modal-body">
          {loading && <div className="modal-loading">Generating report… this may take a moment.</div>}
          {error   && <div className="modal-error">{error}</div>}

          {digest && (
            <>
              {/* Bench Health */}
              <div className="digest-section">
                <div className="digest-section-label">Bench Health</div>
                <div className="digest-health-row">
                  <span className={`health-badge ${HEALTH_CSS[digest.bench_health.status] ?? ''}`}>
                    {digest.bench_health.status}
                  </span>
                  <span className="digest-health-stats">
                    Total: {digest.bench_health.total_bench}&nbsp;&nbsp;|&nbsp;&nbsp;
                    Current: {digest.bench_health.current_bench}&nbsp;&nbsp;|&nbsp;&nbsp;
                    Future: {digest.bench_health.future_bench}&nbsp;&nbsp;|&nbsp;&nbsp;
                    At Risk: {digest.bench_health.at_risk_count}
                  </span>
                </div>
              </div>

              {/* Executive Summary */}
              <div className="digest-section">
                <div className="digest-section-label">Executive Summary</div>
                <p className="digest-summary">{digest.executive_summary}</p>
              </div>

              {/* Top Immediate Actions */}
              <div className="digest-section">
                <div className="digest-section-label">Top Immediate Actions</div>
                {digest.top_actions.length === 0 ? (
                  <div className="digest-empty">No immediate actions</div>
                ) : (
                  <ol className="digest-actions-list">
                    {digest.top_actions.map((a, i) => (
                      <li key={i} className="digest-action-item">{a.action}</li>
                    ))}
                  </ol>
                )}
              </div>

              {/* Threshold Breaches */}
              <div className="digest-section">
                <div className="digest-section-label">Threshold Breaches</div>
                {digest.threshold_breaches.length === 0 ? (
                  <div className="digest-empty">No active threshold breaches</div>
                ) : (
                  <ul className="digest-breach-list">
                    {digest.threshold_breaches.map((b, i) => (
                      <li key={i} className="digest-breach-item">
                        <span className="digest-breach-slice">{b.org_slice}</span>
                        <span className="digest-breach-detail">
                          bench={b.current_bench_count}, threshold={b.bench_threshold}, breach=+{b.breach_amount}
                        </span>
                        <span className={`badge b-${b.alert_severity.toLowerCase()}`}>{b.alert_severity}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              {/* Freeze Recommendations */}
              <div className="digest-section">
                <div className="digest-section-label">Hiring Freeze Recommendations</div>
                {digest.freeze_recommendations.length === 0 ? (
                  <div className="digest-empty">No freeze recommendations</div>
                ) : (
                  <ul className="digest-breach-list">
                    {digest.freeze_recommendations.map((f, i) => (
                      <li key={i} className="digest-breach-item">
                        <span className="digest-breach-slice">{f.skill}</span>
                        <span className="digest-breach-detail">
                          supply={f.total_supply}, demand={f.open_demand_count}, surplus=+{f.supply_surplus}
                        </span>
                        <span className="badge b-freeze">Freeze</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              {/* Releases in 30 days */}
              <div className="digest-section">
                <div className="digest-section-label">Releases in Next 30 Days</div>
                <div className="digest-releases-count">{digest.releases_in_30_days}</div>
              </div>

              <div className="digest-advisory">Advisory only — generated by Bench Agent</div>
            </>
          )}
        </div>

        <div className="modal-footer">
          <button className="modal-cancel-btn" onClick={onClose}>Close</button>
          <button className="copy-btn" onClick={handleDownloadTxt} disabled={!digest || loading}
            style={{ marginRight: 8 }}>
            ⬇ Download .txt
          </button>
          <button className="copy-btn" onClick={handleCopy} disabled={!digest || loading}>
            {copied ? '✓ Copied!' : 'Copy Report'}
          </button>
        </div>
      </div>
    </div>
  )
}
